# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4f2014982d0a489b8be7073c49ba9131344b139183c8265c95321ddb6440ec946ac8cb285e5404ac24cb86569e4d76808bdca1a52367a38e326358cef2ef824

test:
  secret_key_base: 3656a372c9e9350142873357c4c8bf263c9b1160a3c470ac1dd21f8fb4abbf9309fedcd0fcd2804eedfcce4f991106b4986d425c87a4a089182e0d82c6ed49dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
